name: designer
description: Design manager package.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^4.1.1
  fluttertoast: ^8.2.1
  pin_code_fields: ^7.4.0
  shimmer: ^2.0.0
  timer_count_down: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/image_picker/
